name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl
          pip install PyGithub
              

      - name: Raise PR in GitHub
        run: python pr3.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
      
      - name: Upload PR links as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pr-links
          path: |
            pr_links.xlsx
            pr_links.txt
